<a href="https://colab.research.google.com/github/ALgosZen/DataAnalysiswithPython/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import sys

In [ ]:
a = np.array([1,2,3,5,6,6])
b = np.array([4,6,7,9,12,34])

In [ ]:
a[0],b[2]

(1, 7)

In [ ]:
a[1:-1]

array([2, 3, 5, 6])

In [ ]:
a[:3]

array([1, 2, 3])

In [ ]:
a[[1,2]]

array([2, 3])

In [ ]:
a[a>=2]

array([2, 3, 5, 6, 6])